# Copyright Contributors to the Open Cluster Management project

FROM registry.ci.openshift.org/stolostron/builder:nodejs18-linux
WORKDIR /app
# Copy only package.json and package-lock.json so that the docker cache hash only changes if those change
# This will cause the npm ci to only rerun if the package.json or package-lock.json changes
COPY . ./
RUN npm ci --no-optional --legacy-peer-deps

CMD ["npm", "start"]
